"""Refatorar pedidos: criar order_items e ajustar relacionamentos

Revision ID: e2ce49ea49e9
Revises: 80bae53058dc
Create Date: 2026-02-03 17:48:53.815749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores da migration
revision: str = 'e2ce49ea49e9'
down_revision: Union[str, Sequence[str], None] = '80bae53058dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica alterações no schema do banco."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverte alterações aplicadas no upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
